@startuml modelo_dominio
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam monochrome false
skinparam shadowing false
hide circle
hide empty methods

class Emisor {
    potencia
}

class Luz {
    longitud
}

class Obstaculo {
    capacidadReflectiva
}

Emisor --> Luz : emite
Obstaculo --> Luz : absorbe
@enduml
